###
GET http://localhost:3000/league.json

###
GET http://localhost:3000/league/21.json

###
GET http://localhost:3000/league.json
Contest-type: application/json

{
  "name": "Jak'Sho",
  "origin": "Mythic",
  "picture": "https://pbs.twimg.com/media/FhyscoGWYAErGea.png",
  "power_level": "50"
}